#!/usr/bin/env python3
"""Build the SecondBrain catalog: INDEX.md + .brain/manifest.json.

Stdlib only. Walks every note's frontmatter, validates it, groups notes by
domain into a human-readable INDEX.md, catalogs skills, and emits a
machine-readable manifest. Modeled on Sarthib7/agentsmith build-index.py.

Exit code is non-zero if any note fails validation.
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import common  # noqa: E402


def build() -> int:
    notes = list(common.iter_notes())
    skills = list(common.iter_skills())

    by_domain: dict[str, list[common.Note]] = defaultdict(list)
    errors: list[str] = []
    for note in notes:
        by_domain[note.domain].append(note)
        for err in note.errors:
            errors.append(f"{note.rel_path}: {err}")

    write_index_md(by_domain, skills, total=len(notes))
    write_manifest(notes, skills)

    # Summary
    print("SecondBrain catalog")
    for domain in sorted(by_domain):
        print(f"  {domain:16s} {len(by_domain[domain]):3d} notes")
    print(f"  {'skills':16s} {len(skills):3d}")
    print(f"  {'TOTAL notes':16s} {len(notes):3d}")

    if errors:
        print(f"\n{len(errors)} validation error(s):", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1
    return 0


def write_index_md(by_domain, skills, total: int) -> None:
    lines: list[str] = []
    lines.append("# 🧠 SecondBrain — Index")
    lines.append("")
    lines.append(f"_{total} notes across {len(by_domain)} domains · "
                 f"{len(skills)} skills. Generated by `scripts/build_index.py` — do not edit by hand._")
    lines.append("")

    for domain in sorted(by_domain):
        domain_notes = by_domain[domain]
        lines.append(f"## {domain}  ({len(domain_notes)})")
        lines.append("")
        lines.append("| Note | Tags | Summary |")
        lines.append("| --- | --- | --- |")
        for note in sorted(domain_notes, key=lambda n: n.rel_path):
            tags = ", ".join(f"`{t}`" for t in note.tags) or "—"
            summary = common.first_sentence(note.body) or "—"
            link = f"[{note.title}]({note.rel_path})"
            lines.append(f"| {link} | {tags} | {summary} |")
        lines.append("")

    if skills:
        lines.append("## 🛠 Skills")
        lines.append("")
        lines.append("| Skill | Description |")
        lines.append("| --- | --- |")
        for skill in skills:
            desc = (skill["description"] or "—").replace("|", "\\|")
            lines.append(f"| `{skill['name']}` (`skills/{skill['dir']}`) | {desc} |")
        lines.append("")

    out = os.path.join(common.ROOT, "INDEX.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {os.path.relpath(out, common.ROOT)}")


def write_manifest(notes, skills) -> None:
    os.makedirs(common.BRAIN_DIR, exist_ok=True)
    manifest = {
        "notes": [
            {
                "path": n.rel_path,
                "title": n.title,
                "domain": n.domain,
                "tags": n.tags,
                "source": n.source,
                "date": n.date,
            }
            for n in notes
        ],
        "skills": skills,
        "domains": sorted({n.domain for n in notes}),
        "count": len(notes),
    }
    out = os.path.join(common.BRAIN_DIR, "manifest.json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
    print(f"wrote {os.path.relpath(out, common.ROOT)}")


if __name__ == "__main__":
    raise SystemExit(build())
